-- ABA Group — Демо өнімдерді products кестесіне қосу
-- Supabase SQL Editor-де жаңа сұраныс ашып, осы файлдың барлығын қойып, "Run" басыңыз.
-- Бұл тауарларды кейін Admin панельден (aba-group-gamma.vercel.app/admin) өңдеуге/жоюға болады.

insert into products (category_id, sku, brand, price, old_price, stock, icon, name_kz, name_ru, name_en, desc_kz, desc_ru, desc_en) values
('electronics','EL-1001','SoundMax',24900,32000,18,'🎧','Сымсыз құлаққап Pro','Беспроводные наушники Pro','Wireless Headphones Pro','Шуды басатын, 30 сағат жұмыс уақыты бар сымсыз құлаққап.','Беспроводные наушники с шумоподавлением, 30 часов работы.','Noise-cancelling wireless headphones with 30h battery life.'),
('electronics','EL-1002','TimeTech',54900,null,9,'⌚','Смарт сағат Series 5','Смарт-часы Series 5','Smart Watch Series 5','Денсаулық мониторингі, GPS және 7 күндік батарея.','Мониторинг здоровья, GPS и 7 дней автономности.','Health monitoring, GPS and 7-day battery.'),
('electronics','EL-1003','ClearShot',189000,210000,4,'📷','4K экшн камера','Экшн-камера 4K','4K Action Camera','Су өткізбейтін корпус, тұрақтандырғышы бар 4K бейне.','Водонепроницаемый корпус, стабилизация 4K видео.','Waterproof housing with 4K video stabilization.'),
('home','HM-2001','HomeStyle',8900,null,40,'🕯️','Хош иісті шам жинағы','Набор ароматических свечей','Scented Candle Set','Табиғи балауыздан жасалған 3 хош иісті шам жинағы.','Набор из 3 свечей из натурального воска.','Set of 3 natural wax scented candles.'),
('home','HM-2002','KitchenPro',34900,41000,15,'🍽️','Керамикалық ыдыс жинағы','Набор керамической посуды','Ceramic Dinnerware Set','16 бөлімнен тұратын премиум керамикалық ыдыс жинағы.','Премиальный набор керамической посуды из 16 предметов.','Premium 16-piece ceramic dinnerware set.'),
('home','HM-2003','HomeStyle',15900,null,22,'🧺','Сақтауға арналған себет','Корзина для хранения','Storage Basket','Табиғи ротаннан тоқылған, интерьерге сай себет.','Плетёная корзина из натурального ротанга.','Woven natural rattan storage basket.'),
('auto','AT-3001','AutoGuard',12900,null,30,'🚙','Автокөлік ковриктер жинағы','Комплект автоковриков','Car Floor Mat Set','Су өткізбейтін, барлық маусымға жарамды коврик жинағы.','Водонепроницаемые всесезонные автоковрики.','Waterproof all-season car floor mats.'),
('auto','AT-3002','PowerCell',45900,52000,11,'🔋','Автокөлік аккумуляторы 60Ah','Автомобильный аккумулятор 60Ah','Car Battery 60Ah','Ұзақ қызмет ету мерзімі бар сенімді аккумулятор.','Надёжный аккумулятор с долгим сроком службы.','Reliable long-life 60Ah car battery.'),
('construction','CN-4001','BuildCo',2900,null,500,'🧱','Керамикалық плитка (м²)','Керамическая плитка (м²)','Ceramic Tile (per m²)','Травертин тектес керамикалық плитка, интерьер мен экстерьерге.','Керамическая плитка под травертин.','Travertine-style ceramic tile for interior and exterior.'),
('construction','CN-4002','BuildCo',78000,89000,6,'🪟','Металл-пластик терезе','Металлопластиковое окно','PVC Window Unit','Энергия үнемдейтін екі камералы терезе жүйесі.','Энергоэффективная двухкамерная оконная система.','Energy-efficient double-chamber window system.'),
('security','SC-5001','SecureView',32900,null,14,'📹','IP камера жинағы (4 дана)','Комплект IP-камер (4 шт)','IP Camera Kit (4pcs)','Түнде көру функциясы бар, қашықтан қадағалау камералары.','Камеры с ночным видением и удалённым доступом.','Night-vision cameras with remote monitoring.'),
('security','SC-5002','LockX',68900,75000,8,'🔐','Смарт есік құлпы X10','Умный дверной замок X10','Smart Door Lock X10','Саусақ ізі мен қашықтан ашу мүмкіндігі бар смарт құлып.','Умный замок с отпечатком пальца и удалённым доступом.','Fingerprint smart lock with remote access.'),
('islamic','IS-6001','Barakah',6900,null,60,'📿','Тәсбих (ағаш)','Тасбих (дерево)','Wooden Tasbih','Табиғи ағаштан қолдан жасалған тәсбих.','Тасбих ручной работы из натурального дерева.','Handcrafted natural wood tasbih.'),
('islamic','IS-6002','Barakah',19900,null,25,'🕋','Намазхана кілемше жинағы','Набор молитвенных ковриков','Prayer Mat Set','Жұмсақ, тасымалдауға ыңғайлы намазхана кілемшесі.','Мягкий и компактный молитвенный коврик.','Soft, portable prayer mat.'),
('other','OT-7001','Nomad',14900,17900,33,'🎒','Саяхат рюкзагы 40L','Туристический рюкзак 40L','Travel Backpack 40L','Су өткізбейтін, көп бөлімді саяхат рюкзагы.','Водонепроницаемый многосекционный рюкзак.','Waterproof multi-compartment travel backpack.')
on conflict (sku) do nothing;
